### ISSUE TITLE
Cant create JVM Error

### ISSUE THREAD

**Issue by avinashmkb** [louismullie/stanford-core-nlp#13]
I have installed RJB and the followed all instructions as suggested in your gem documentation.

Have installed JAVA 1.6 and set the $JAVA_HOME TO /home/avinash/jdk1.6.0_38 similarly i have set  $LD_LIBRARY_PATH=/home/avinash/jdk1.6.0_38/lib

Also defined Ruby Enviroment variables 

ENV['JAVA_HOME'] = "/home/avinash/jdk1.6.0_38"
ENV['LD_LIBRARY_PATH']="/home/avinash/jdk1.6.0_38/lib"

[root@avinash shoutout_railsengine]# IRB
-bash: IRB: command not found
[root@avinash shoutout_railsengine]# irb
irb(main):001:0> require 'stanford-core-nlp'
=> true
irb(main):002:0> StanfordCoreNLP.log_file = 'log.txt'
=> "log.txt"
irb(main):003:0> StanfordCoreNLP.set_model('pos.model', 'english-left3words-distsim.tagger')
=> "taggers/english-left3words-distsim.tagger"
irb(main):004:0> text = 'Angela Merkel met Nicolas Sarkozy on January 25th in '
=> "Angela Merkel met Nicolas Sarkozy on January 25th in "
irb(main):005:0> pipeline =  StanfordCoreNLP.load(:tokenize, :ssplit, :pos, :lemma, :parse, :ner, :dcoref)
RuntimeError: can't create Java VM
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/jar_loader.rb:19:in `load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/jar_loader.rb:19:in`init'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/jar_loader.rb:36:in `load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/binding.rb:56:in`load_jar'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/binding.rb:64:in `block in load_default_jars'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/binding.rb:61:in`each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/binding.rb:61:in `load_default_jars'
        from /usr/local/lib/ruby/gems/1.9.1/gems/bind-it-0.2.0/lib/bind-it/binding.rb:48:in`bind'
        from /usr/local/lib/ruby/gems/1.9.1/gems/stanford-core-nlp-0.3.5/lib/stanford-core-nlp.rb:118:in `load'
        from (irb):5
        from /usr/local/bin/irb:12:in`<main>'

**Comment by arbox** [comment]
Please be patient, we are working on this issue!
