### ISSUE TITLE
SemanticGraphCoreAnnotations missing

### ISSUE THREAD

**Issue by heathd** [louismullie/stanford-core-nlp#34]
Hi

I'm new to Stanford NLP, just experimenting with it, so please excuse any glaring mistakes!

I installed your gem the newest `stanford-corenlp-full-2014-10-31` and `stanford-postagger-2014-10-26`. 

I'm using the gem version `0.5.1`.

Following your instructions I configured StanfordCoreNLP to use these libraries. See this gist:

https://gist.github.com/heathd/b6fa778f682cec8e688c

Upon running this script I got the following error:

```
/Users/davidheath/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/stanford-core-nlp-0.5.1/lib/stanford-core-nlp/bridge.rb:48:in `method_missing': edu.stanford.nlp.trees.semgraph.SemanticGraphCoreAnnotations$BasicDependenciesAnnotation (ClassNotFoundException)
	from /Users/davidheath/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/stanford-core-nlp-0.5.1/lib/stanford-core-nlp/bridge.rb:48:in `get'
	from test.rb:33:in `block in <main>'
	from /Users/davidheath/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bind-it-0.2.7/lib/bind-it/rjb_proxy.rb:22:in `each'
	from test.rb:31:in `<main>'
```

after some digging around I found the `config.rb` file line 354 from:

```
      'nlp.trees.semgraph.SemanticGraphCoreAnnotations' => [
        'BasicDependenciesAnnotation',
        'CollapsedCCProcessedDependenciesAnnotation',
        'CollapsedDependenciesAnnotation'
      ],
```

to 

```
      'nlp.semgraph.SemanticGraphCoreAnnotations' => [
        'BasicDependenciesAnnotation',
        'CollapsedCCProcessedDependenciesAnnotation',
        'CollapsedDependenciesAnnotation'
      ],
```

I suppose that this library must have been moved during a recent release of the Stanford NLP java library.

I noticed that this change was included in the commit from @efrat-safanov in e0f12bd6. So I guess that you'll include this change in a future release of the gem. 

Possibly nothing to do here apart from making it clear somewhere that the current gem release doesn't work with stanford nlp 3.5.0?

Thanks!

David

**Comment by arbox** [comment]
Please be patient, we are working on this issue!
